nmap <buffer> <CR> <plug>(bqn_eval_line)
xmap <buffer> <CR> <plug>(bqn_eval_range)
nmap <buffer> <leader>bf <plug>(bqn_eval_file)
nmap <buffer> <leader>bc <plug>(bqn_clear_after_line)
nmap <buffer> <leader>bC <plug>(bqn_clear_file)
xmap <buffer> <leader>bc <plug>(bqn_clear_range)
xmap <buffer> <leader>bs <plug>(start_repl)
nmap <buffer> <leader>bt <plug>(bqn_constant_eval)
