nmap <buffer> <CR> <plug>(bqn_eval_line)
xmap <buffer> <CR> <plug>(bqn_eval_range)
nmap <buffer> <Leader>bf <plug>(bqn_eval_file)
nmap <buffer> <Leader>bc <plug>(bqn_clear_after_line)
nmap <buffer> <Leader>bC <plug>(bqn_clear_file)
xmap <buffer> <Leader>bc <plug>(bqn_clear_range)
xmap <buffer> <Leader>bs <plug>(start_repl)
nmap <buffer> <Leader>bt <plug>(bqn_constant_eval)
